local sometable = {
   {
      type = "BfGuiCreateWindowContainerObj",
      __selected_layer = -1,
      __name = "",
      __old_size = { 150, 150 },
      __header_button_size = { 20, 20 },
      base = {
         type = "BfGuiCreateWindowContainer",
         __id = 5,
         __str_id = "##CreateWindow_5",
         __is_button = 15,
         __is_force_render = 0,
         __is_render_header = 1,
         __is_collapsed = 0,
         __resize_button_size = { 10, 10 },
         __bot_resize_button_size = { 10, 10 },
         __window_pos = { 0, 0 },
         __window_size = { 150, 150 },
         __containers = {
            {
               type = "BfGuiCreateWindowContainerObj",
               __selected_layer = -1,
               __name = "",
               __old_size = { 150, 150 },
               __header_button_size = { 20, 20 },
               base = {
                  type = "BfGuiCreateWindowContainer",
                  __id = 9,
                  __str_id = "##CreateWindow_9",
                  __is_button = 15,
                  __is_force_render = 0,
                  __is_render_header = 1,
                  __is_collapsed = 0,
                  __resize_button_size = { 10, 10 },
                  __bot_resize_button_size = { 10, 10 },
                  __window_pos = { 0, 0 },
                  __window_size = { 150, 150 },
                  __containers = {},
               },
            },
         },
      },
   },
   {
      type = "BfGuiCreateWindowContainer",
      __id = 13,
      __str_id = "##CreateWindow_13",
      __is_button = 15,
      __is_force_render = 0,
      __is_render_header = 1,
      __is_collapsed = 0,
      __resize_button_size = { 10, 10 },
      __bot_resize_button_size = { 10, 10 },
      __window_pos = { 0, 0 },
      __window_size = { 150, 150 },
      __containers = {},
   },
}
return sometable
