A = {
   __create_info = {
      type = "BfBladeSectionCreateInfo",
      width = 1.0000,
      install_angle = 102.0000,
      inlet_angle = 25.0000,
      outlet_angle = 42.0000,
      inlet_surface_angle = 15.0000,
      outlet_surface_angle = 15.0000,
      inlet_radius = 0.0250,
      outlet_radius = 0.0050,
      border_length = 20.0000,
      start_vertex = { 0, 0, 0 },
      grow_direction = { 0, 1, 0 },
      up_direction = { 0, 0, 1 },
   },
   __mode = 0,
   base = {
      type = "BfGuiCreateWindowContainerObj",
      __selected_layer = -1,
      __name = "",
      __old_size = { 500, 350 },
      __header_button_size = { 20, 20 },
      base = {
         type = "BfGuiCreateWindowContainer",
         __id = 53,
         __str_id = "##CreateWindow_53",
         __is_button = 3,
         __is_force_render = 0,
         __is_render_header = 1,
         __is_collapsed = 1,
         __resize_button_size = { 10, 10 },
         __bot_resize_button_size = { 10, 10 },
         __window_pos = { 0, 0 },
         __window_size = { 500, 80 },
         __containers = {},
      },
   },
}
